"""Self-sent event triage path (#107).

When the operator emails THEMSELVES (``From == To`` on the same
account, or any of the account's aliases) and the message looks like
a personal event reminder, this action extracts the event and writes
it to the operator's ``self_schedule`` calendar.

Trigger conditions (all must hold):

* ``message.sender_address`` matches one of the account's addresses
  (primary + ``config.aliases``, case-folded).
* The classifier categorised the message as ``self-event``.
* The account is NOT HIPAA-flagged. Self-sent personal events
  intentionally bypass the HIPAA write surface — events on a HIPAA
  calendar can carry PHI and would leak through downstream digests
  / API listings.
* The account is NOT acting as a calendar surrogate target. We only
  write to the OPERATOR'S own calendar; surrogating self-sent
  events to a delegate's calendar muddies ownership.
* The account has a ``self_schedule`` calendar configured (operator
  picked one from the per-account calendar role table).
* The message itself was NOT generated by email-triage (the
  ``X-Email-Triage`` header guard) — same loop-prevention check the
  inline path uses.

Each gate failure returns ``ActionResult.SKIPPED`` with a structured
``reason``. The runner records the row regardless so the operator
can see why the action didn't fire.

Event-shape extraction is deliberately conservative: simple regex
sweeps for date / time / location. When parse fails, the action
still returns COMPLETED with ``data["calendar_write"] = "skipped"``
— the classifier already decided this is a self-event, so the row
gets logged, but no calendar pollution from a bad parse.
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timedelta, timezone
from typing import Any

from email_triage.actions.base import (
    Action,
    check_idempotent_already_done,
    record_idempotent_done,
)
from email_triage.engine.models import (
    ActionOutput,
    ActionResult,
    CalendarEvent,
    Classification,
    EmailMessage,
    FlowState,
)
from email_triage.mail_headers import get_triage_header
from email_triage.providers.base import EmailProvider
from email_triage.providers.calendar_base import (
    CalendarProvider,
    CalendarScopeError,
)

log = logging.getLogger("email_triage.actions.self_sent_event")


# ---------------------------------------------------------------------------
# Address matching
# ---------------------------------------------------------------------------

_ADDR_RE = re.compile(r"<\s*([^<>\s]+@[^<>\s]+)\s*>")


def _extract_address(raw: str) -> str:
    """Return the bare email address from a possibly-displayname-wrapped
    sender string. ``"Operator A <op@example.com>"`` -> ``"op@example.com"``.
    Bare addresses pass through. Case-folded; surrounding whitespace
    stripped. Empty string when no address is found.
    """
    if not raw:
        return ""
    s = str(raw).strip()
    m = _ADDR_RE.search(s)
    if m:
        return m.group(1).strip().lower()
    # Bare address — strip any obvious junk.
    return s.split()[-1].strip("<>").lower()


# ---------------------------------------------------------------------------
# Subject normalisation
# ---------------------------------------------------------------------------

_SUBJECT_PREFIX_RE = re.compile(r"^\s*(?:re|fwd?|fw)\s*:\s*", re.IGNORECASE)


def _strip_reply_prefix(subject: str) -> str:
    """Strip leading ``Re:`` / ``Fwd:`` / ``Fw:`` (any case) from a
    subject. Multiple chained prefixes are stripped iteratively
    (``Re: Re: Lunch`` -> ``Lunch``)."""
    if not subject:
        return ""
    out = subject
    while True:
        new = _SUBJECT_PREFIX_RE.sub("", out, count=1)
        if new == out:
            break
        out = new
    return out.strip()


# ---------------------------------------------------------------------------
# Time-shape extraction
# ---------------------------------------------------------------------------
#
# Conservative parser. The classifier already decided this is a
# self-event; we just look for an unambiguous date+time tuple. When
# multiple candidates appear we take the FIRST in body order — the
# operator's note-to-self pattern usually leads with the time
# ("Coffee Tuesday 3pm with Ops Team about Project X" — the time is
# upfront).
#
# Patterns:
#   "Tuesday 3pm" / "Tue 3:30 PM"          weekday + time
#   "2026-06-01 14:00" / "2026-06-01 2pm"  ISO date + time
#   "June 1 3pm" / "Jun 1 at 14:30"        month + day + time
#
# All parse to UTC datetimes so the event lands consistently.
# Operator's local-tz preference would render correctly downstream
# via the calendar provider's per-account tz config; we don't try
# to second-guess that here.

_WEEKDAYS = {
    "mon": 0, "monday": 0,
    "tue": 1, "tues": 1, "tuesday": 1,
    "wed": 2, "weds": 2, "wednesday": 2,
    "thu": 3, "thur": 3, "thurs": 3, "thursday": 3,
    "fri": 4, "friday": 4,
    "sat": 5, "saturday": 5,
    "sun": 6, "sunday": 6,
}

_MONTHS = {
    "jan": 1, "january": 1,
    "feb": 2, "february": 2,
    "mar": 3, "march": 3,
    "apr": 4, "april": 4,
    "may": 5,
    "jun": 6, "june": 6,
    "jul": 7, "july": 7,
    "aug": 8, "august": 8,
    "sep": 9, "sept": 9, "september": 9,
    "oct": 10, "october": 10,
    "nov": 11, "november": 11,
    "dec": 12, "december": 12,
}


_TIME_RE = re.compile(
    r"(?P<hour>\d{1,2})"
    r"(?::(?P<minute>\d{2}))?"
    r"\s*"
    r"(?P<ampm>am|pm|AM|PM|Am|Pm)?",
)


def _parse_time(text: str) -> tuple[int, int] | None:
    """Return ``(hour_24, minute)`` from a time-shaped string, or None."""
    m = _TIME_RE.match(text.strip())
    if not m:
        return None
    try:
        hour = int(m.group("hour"))
    except (TypeError, ValueError):
        return None
    minute_raw = m.group("minute")
    minute = int(minute_raw) if minute_raw else 0
    ampm = (m.group("ampm") or "").lower()
    if ampm == "pm" and hour < 12:
        hour += 12
    elif ampm == "am" and hour == 12:
        hour = 0
    if not (0 <= hour <= 23 and 0 <= minute <= 59):
        return None
    # Ambiguous: "3" with no ampm and no minute is too vague to count
    # as a time. Require either an explicit am/pm OR a colon-delimited
    # minute OR a two-digit hour ≥ 13 (24-hour clock).
    if not ampm and not minute_raw and hour < 13:
        return None
    return hour, minute


# Combined "weekday + time" sweep.
_WEEKDAY_TIME_RE = re.compile(
    r"\b(?P<weekday>"
    + "|".join(sorted(_WEEKDAYS.keys(), key=len, reverse=True))
    + r")"
    r"\s+(?:at\s+)?"
    r"(?P<time>\d{1,2}(?::\d{2})?\s*(?:am|pm|AM|PM)?)\b",
    re.IGNORECASE,
)

# ISO date + time sweep: 2026-06-01 14:00 / 2026-06-01 2pm
_ISO_DATE_TIME_RE = re.compile(
    r"\b(?P<date>\d{4}-\d{2}-\d{2})"
    r"[\sT]+"
    r"(?:at\s+)?"
    r"(?P<time>\d{1,2}(?::\d{2})?\s*(?:am|pm|AM|PM)?)\b",
)

# Month-name + day + time: June 1 3pm / Jun 1 at 14:30
_MONTH_DAY_TIME_RE = re.compile(
    r"\b(?P<month>"
    + "|".join(sorted(_MONTHS.keys(), key=len, reverse=True))
    + r")"
    r"\s+(?P<day>\d{1,2})(?:st|nd|rd|th)?"
    r"\s+(?:at\s+)?"
    r"(?P<time>\d{1,2}(?::\d{2})?\s*(?:am|pm|AM|PM)?)\b",
    re.IGNORECASE,
)


def _next_weekday(now: datetime, target_weekday: int) -> datetime:
    """Return the next date (>= today) whose weekday matches ``target_weekday``.

    If today's weekday matches, returns today's date (the operator's
    note-to-self for "Tuesday 3pm" sent on Tuesday morning is
    almost always today's 3pm).
    """
    days_ahead = (target_weekday - now.weekday()) % 7
    return now + timedelta(days=days_ahead)


def _extract_event_time(
    body: str, *, now: datetime | None = None,
) -> datetime | None:
    """Return the first plausible event start datetime parsed from
    ``body``, or None.

    ``now`` defaults to ``datetime.now(timezone.utc)``; tests pin it
    for deterministic assertions. Result is tz-aware UTC.
    """
    if not body:
        return None
    now = now or datetime.now(timezone.utc)

    # ISO date + time wins (most specific).
    m = _ISO_DATE_TIME_RE.search(body)
    if m:
        try:
            d = datetime.strptime(m.group("date"), "%Y-%m-%d").date()
        except ValueError:
            d = None
        if d is not None:
            t = _parse_time(m.group("time"))
            if t is not None:
                return datetime(d.year, d.month, d.day, t[0], t[1], tzinfo=timezone.utc)

    # Month name + day + time.
    m = _MONTH_DAY_TIME_RE.search(body)
    if m:
        month = _MONTHS.get(m.group("month").lower())
        try:
            day = int(m.group("day"))
        except (TypeError, ValueError):
            day = None
        if month and day and 1 <= day <= 31:
            t = _parse_time(m.group("time"))
            if t is not None:
                # Year defaults to current; if the resulting date is
                # already in the past relative to ``now``, roll
                # forward a year (operator wrote the note-to-self
                # in late December for a January date).
                year = now.year
                try:
                    candidate = datetime(year, month, day, t[0], t[1], tzinfo=timezone.utc)
                except ValueError:
                    return None
                if candidate < now - timedelta(hours=24):
                    candidate = candidate.replace(year=year + 1)
                return candidate

    # Weekday + time.
    m = _WEEKDAY_TIME_RE.search(body)
    if m:
        wd = _WEEKDAYS.get(m.group("weekday").lower())
        if wd is not None:
            t = _parse_time(m.group("time"))
            if t is not None:
                target = _next_weekday(now, wd)
                return datetime(
                    target.year, target.month, target.day, t[0], t[1],
                    tzinfo=timezone.utc,
                )

    return None


# ---------------------------------------------------------------------------
# Location extraction
# ---------------------------------------------------------------------------

_LOCATION_LINE_RE = re.compile(
    r"(?im)^\s*(?:location|where)\s*[:\-]\s*(?P<loc>.+?)\s*$"
)
# Conferencing URL detection (zoom / meet / teams / webex / generic
# https with conference path hints). We don't validate the URL — just
# carry it through so the calendar UI surfaces it as the location.
_CONFERENCING_URL_RE = re.compile(
    r"https?://(?:[a-z0-9-]+\.)*"
    r"(?:zoom\.us|meet\.google\.com|teams\.microsoft\.com|webex\.com|"
    r"meet\.jit\.si|whereby\.com)"
    r"/[^\s)>]*",
    re.IGNORECASE,
)


def _extract_location(body: str) -> str:
    """Return the first ``Location:`` / ``Where:`` line, or a
    conferencing URL, or empty string. 200-char cap so a malformed
    body can't blow up the event.
    """
    if not body:
        return ""
    m = _LOCATION_LINE_RE.search(body)
    if m:
        return m.group("loc").strip()[:200]
    m = _CONFERENCING_URL_RE.search(body)
    if m:
        return m.group(0).strip()[:200]
    return ""


# ---------------------------------------------------------------------------
# Action
# ---------------------------------------------------------------------------

class SelfSentEventAction(Action):
    """Extract a self-sent event and write it to the self_schedule
    calendar.

    Wired into the runner's action registry; routed by classifier
    category ``self-event``. The first guard checks the inbound is
    actually self-sent — without it, a misrouted self-event
    classification on a stranger's mail wouldn't accidentally write
    to the operator's calendar.
    """

    DEFAULT_DURATION_MINUTES = 30
    BODY_PREVIEW_CHARS = 500

    @property
    def name(self) -> str:
        return "self_sent_event"

    async def execute(
        self,
        flow: FlowState,
        message: EmailMessage,
        classification: Classification,
        provider: EmailProvider,
        config: dict[str, Any] | None = None,
    ) -> ActionOutput:
        # Idempotency short-circuit (PR 6 / C2). On a re-run of the
        # same flow + message the state_bag already carries the
        # previous calendar event id; bail before re-writing.
        prior = check_idempotent_already_done(flow, message, self.name)
        if prior is not None:
            return prior

        state_bag = flow.state_bag if isinstance(flow.state_bag, dict) else {}

        # HIPAA gate — first-class boundary. Account-level flag is
        # the authoritative source; ``message.hipaa`` mirrors it but
        # the runner could be writing this for an account whose
        # flag flipped between fetch + action. Trust the live
        # account.
        acct = state_bag.get("account") or {}
        if message.hipaa or self._is_account_hipaa(state_bag):
            return ActionOutput(
                result=ActionResult.SKIPPED,
                data={"reason": "hipaa_account"},
            )

        # Cross-account surrogate guard. Self-sent events are
        # user-personal — they belong on the operator's OWN
        # calendar, never on a delegate's surrogate target.
        if state_bag.get("calendar_surrogate_active"):
            return ActionOutput(
                result=ActionResult.SKIPPED,
                data={"reason": "cross_account_surrogate"},
            )

        # Loop-prevention. Same shape as the runner's pre-classify
        # short-circuit but defended again here so an action invoked
        # outside the runner (test, API direct call) can't bypass.
        if get_triage_header(message.headers):
            return ActionOutput(
                result=ActionResult.SKIPPED,
                data={"reason": "x_email_triage_header"},
            )

        # From == To (against the account's primary + aliases).
        addresses = state_bag.get("account_addresses") or []
        sender = _extract_address(message.sender)
        if not sender or sender not in {a.lower() for a in addresses}:
            return ActionOutput(
                result=ActionResult.SKIPPED,
                data={"reason": "sender_not_self"},
            )

        # Self-schedule destination.
        dest_calendar_id = state_bag.get("self_schedule_calendar_id")
        if not dest_calendar_id:
            log.info(
                "self-sent event skipped: no self_schedule calendar configured",
                extra={"account_id": state_bag.get("account_id")},
            )
            return ActionOutput(
                result=ActionResult.SKIPPED,
                data={"reason": "no_self_schedule_calendar"},
            )

        cal: CalendarProvider | None = state_bag.get("calendar_provider")
        if cal is None:
            return ActionOutput(
                result=ActionResult.SKIPPED,
                data={"reason": "calendar_not_enabled"},
            )

        # Build event from message.
        summary = _strip_reply_prefix(message.subject) or "Note to self"
        body_preview = (message.body_text or "")[: self.BODY_PREVIEW_CHARS]
        ts_iso = datetime.now(timezone.utc).isoformat()
        description = (
            f"{body_preview}\n\n"
            f"Auto-extracted from self-sent message at {ts_iso}"
        )
        location = _extract_location(message.body_text or "")
        start = _extract_event_time(message.body_text or "")

        if start is None:
            # Classifier said self-event but parse failed — log INFO
            # and skip the calendar write. Don't error — we still
            # persisted the triage_runs row via the runner.
            log.info(
                "self-sent event: no parseable time",
                extra={"account_id": state_bag.get("account_id")},
            )
            return ActionOutput(
                result=ActionResult.COMPLETED,
                data={
                    "calendar_write": "skipped",
                    "reason": "no_parseable_time",
                    "summary": summary,
                },
            )

        end = start + timedelta(minutes=self.DEFAULT_DURATION_MINUTES)
        event = CalendarEvent(
            event_id="",
            calendar_id=str(dest_calendar_id),
            summary=summary,
            description=description,
            location=location,
            start=start,
            end=end,
            all_day=False,
            organizer="",
            attendees=[],
            status="confirmed",
        )

        try:
            new_event_id = await cal.create_event(
                event, calendar_id=str(dest_calendar_id),
            )
        except CalendarScopeError as e:
            return ActionOutput(
                result=ActionResult.FAILED,
                error=f"calendar_scope_missing: {e}",
            )
        except NotImplementedError:
            # Provider doesn't support write (IMAP-stub / CalDAV-parked
            # per #108). Degrade cleanly.
            return ActionOutput(
                result=ActionResult.SKIPPED,
                data={
                    "reason": "provider_create_event_unsupported",
                    "summary": summary,
                },
            )
        except Exception as e:
            return ActionOutput(
                result=ActionResult.FAILED,
                error=f"create_event_error: {e}",
            )

        # Per-message dedup stamp (#107 audit + dedup). Best-effort —
        # a DB blip here must not cause an action failure.
        db = state_bag.get("db")
        rfc_id = (message.headers or {}).get("Message-Id") or (
            message.headers or {}).get("Message-ID") or message.message_id
        account_id = state_bag.get("account_id")
        if db is not None and account_id and rfc_id:
            try:
                from email_triage.web.db import mark_triaged
                mark_triaged(db, int(account_id), str(rfc_id))
            except Exception:
                pass

        record_idempotent_done(
            flow, message, self.name, external_id=str(new_event_id),
        )

        return ActionOutput(
            result=ActionResult.COMPLETED,
            data={
                "calendar_write": "ok",
                "event_id": str(new_event_id),
                "calendar_id": str(dest_calendar_id),
                "summary": summary,
                "start": start.isoformat(),
                "end": end.isoformat(),
                "location": location,
            },
        )

    @staticmethod
    def _is_account_hipaa(state_bag: dict[str, Any]) -> bool:
        """Resolve HIPAA from the runner's stashed account context.

        ``state_bag["account"]`` is the live account dict (preferred);
        ``state_bag["account_hipaa"]`` is a pre-computed boolean some
        callers stash. Either path returns the same answer.
        """
        if state_bag.get("account_hipaa") is True:
            return True
        acct = state_bag.get("account")
        if isinstance(acct, dict):
            from email_triage.triage_logging import is_account_hipaa
            return is_account_hipaa(acct)
        return False
